CLASS zbp_prodduct_ic_test DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zbp_prodduct_ic_test  IMPLEMENTATION.
ENDCLASS.
