CLASS zbp_r_salesordertp_test DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zbp_r_salesordertp_test  IMPLEMENTATION.
ENDCLASS.
