CLASS zbp_r_product_ic000 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_product_ic000 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_r_product_ic000 IMPLEMENTATION.
ENDCLASS.
